webtalk_init -webtalk_dir C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_final_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Sun Oct 31 10:49:03 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "211819952_0_0_421" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "d8c302af-fccf-4d30-8967-1eccda5fc276" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f1ec9f782f4849069fd923ff5bdc1511" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "452" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 5 3600 6-Core Processor              " -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3600 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "2" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "34.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key File_Counter -value "44" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Command -value "xelab" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Vhdl2008 -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key GenDLL -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key SDFModeling -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key HWCosim -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key DPI_Used -value "false" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Debug -value "typical" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key Simulation_Image_Code -value "1169 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Image_Data -value "370 KB" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Nets -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Processes -value "7059" -context "xsim\\usage"
webtalk_add_data -client xsim -key Total_Instances -value "2186" -context "xsim\\usage"
webtalk_add_data -client xsim -key Xilinx_HDL_Libraries_Used -value "secureip " -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Time -value "5.11_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Compiler_Memory -value "401132_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2228807489 -regid "211819952_0_0_421" -xml C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_final_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_final_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_final_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
