# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in.xci
# IP: The module: 'Memory_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory_in'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in.xci
# IP: The module: 'Memory_in' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Memory_in'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
