# 
# Synthesis run script generated by Vivado
# 

proc create_report { reportName command } {
  set status "."
  append status $reportName ".fail"
  if { [file exists $status] } {
    eval file delete [glob $status]
  }
  send_msg_id runtcl-4 info "Executing : $command"
  set retval [eval catch { $command } msg]
  if { $retval != 0 } {
    set fp [open $status w]
    close $fp
    send_msg_id runtcl-5 warning "$msg"
  }
}
create_project -in_memory -part xc7a100tcsg324-1

set_param project.singleFileAddWarning.threshold 0
set_param project.compositeFile.enableAutoGeneration 0
set_param synth.vivado.isSynthRun true
set_msg_config -source 4 -id {IP_Flow 19-2162} -severity warning -new_severity info
set_property webtalk.parent_dir C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.cache/wt [current_project]
set_property parent.project_path C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.xpr [current_project]
set_property XPM_LIBRARIES XPM_MEMORY [current_project]
set_property default_lib xil_defaultlib [current_project]
set_property target_language VHDL [current_project]
set_property board_part digilentinc.com:nexys4_ddr:part0:1.1 [current_project]
set_property ip_output_repo c:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.cache/ip [current_project]
set_property ip_cache_permissions {read write} [current_project]
read_vhdl -library xil_defaultlib {
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/FA.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/FIFO.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/FSM.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/MULT_SIMD3X3.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/MUX13.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/MUX9.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/Mux12.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/MuxExt.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/Mux_8.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/RCA_24.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/adder_level_1.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/adder_level_2.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/adder_level_4.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/adder_lever_3.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/mux1.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/mux11.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/mux14.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/mux20.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/mux32.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/pixel_final_sum.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/reg_file.vhd
  C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/new/CONV_SIMD_3X3.vhd
}
read_ip -quiet C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out.xci
set_property used_in_implementation false [get_files -all c:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out_ooc.xdc]

read_ip -quiet C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in.xci
set_property used_in_implementation false [get_files -all c:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/sources_1/ip/Memory_in/Memory_in_ooc.xdc]

# Mark all dcp files as not used in implementation to prevent them from being
# stitched into the results of this synthesis run. Any black boxes in the
# design are intentionally left as such for best results. Dcp files will be
# stitched into the design at a later time, either when this synthesis run is
# opened, or when it is stitched into a dependent implementation run.
foreach dcp [get_files -quiet -all -filter file_type=="Design\ Checkpoint"] {
  set_property used_in_implementation false $dcp
}
read_xdc C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/constrs_1/new/constraint.xdc
set_property used_in_implementation false [get_files C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/ConvSimd.srcs/constrs_1/new/constraint.xdc]


synth_design -top CONV_SIMD_3X3 -part xc7a100tcsg324-1


# disable binary constraint mode for synth run checkpoints
set_param constraints.enableBinaryConstraints false
write_checkpoint -force -noxdef CONV_SIMD_3X3.dcp
create_report "synth_1_synth_report_utilization_0" "report_utilization -file CONV_SIMD_3X3_utilization_synth.rpt -pb CONV_SIMD_3X3_utilization_synth.pb"
