@echo off
REM ****************************************************************************
REM Vivado (TM) v2017.4 (64-bit)
REM
REM Filename    : simulate.bat
REM Simulator   : Xilinx Vivado Simulator
REM Description : Script for simulating the design by launching the simulator
REM
REM Generated by Vivado on Sun Oct 31 11:04:11 +0100 2021
REM SW Build 2086221 on Fri Dec 15 20:55:39 MST 2017
REM
REM Copyright 1986-2017 Xilinx, Inc. All Rights Reserved.
REM
REM usage: simulate.bat
REM
REM ****************************************************************************
call xsim TB_final_time_impl -key {Post-Implementation:sim_1:Timing:TB_final} -tclbatch TB_final.tcl -view C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/TB_MULT_behav1.wcfg -view C:/Users/andry/Desktop/Digitale/Vivado/ConvSimd_FINAL/ConvSimd/tb_fsm_behav.wcfg -log simulate.log
if "%errorlevel%"=="0" goto SUCCESS
if "%errorlevel%"=="1" goto END
:END
exit 1
:SUCCESS
exit 0
