webtalk_init -webtalk_dir C:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_REG_FILE_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Thu Oct 21 19:44:01 2021" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2017.4 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "2086221" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "40ebcf12-0841-4877-b295-5b169874033e" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "f1ec9f782f4849069fd923ff5bdc1511" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "11" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Microsoft Windows 8 or later , 64-bit" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "Intel(R) Core(TM) i7-6500U CPU @ 2.50GHz" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "2592 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "12.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "0 ps" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "0" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "38.06_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "14652_KB" -context "xsim\\usage"
webtalk_transmit -clientid 3584122915 -regid "" -xml C:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_REG_FILE_behav/webtalk/usage_statistics_ext_xsim.xml -html C:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_REG_FILE_behav/webtalk/usage_statistics_ext_xsim.html -wdm C:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.sim/sim_1/behav/xsim/xsim.dir/TB_REG_FILE_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
