# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: c:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out.xci
# IP: The module: 'Mem_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem_out'. Do not add the DONT_TOUCH constraint.
set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet

# IP: c:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out.xci
# IP: The module: 'Mem_out' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: c:/Users/Matteo/Desktop/Sistemi_Digitali/ConvSimd/ConvSimd.srcs/sources_1/ip/Mem_out/Mem_out_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'Mem_out'. Do not add the DONT_TOUCH constraint.
#dup# set_property DONT_TOUCH TRUE [get_cells U0 -quiet] -quiet
